= Requirements

== Actors

Cyclist:: A happy person that likes to sweat.
Plan Owner:: A person who creates training plans. Training plans can be created for private use or can be published for other cyclists' usage.

== User stories

[plantuml, actors, png]
....
skinparam handwritten true
top to bottom direction
:Cyclist:
:Plan Owner: as Trainer
(Training plan selection) as UC01
(Display training plan) as UC02
(Upload training data) as UC03
(Display training) as UC04
(Withdraw plan) as UC05
(Create training plan) as UC11
(Create training) as UC12

:Cyclist: --> UC01
:Cyclist: -left-> UC02
:Cyclist: -> UC03
:Cyclist: -up-> UC04
:Cyclist: --> UC05
UC03 .> UC04 : extends
Trainer --> UC11
Trainer --> UC12
....

=== Training plan selection

I would like to select one of the available training plans.

The plan becomes immediately effective.
The plan stays selected until its last day, or the cyclist select <<Withdraw plan>> use case.
Once last day of the training plan passes, the plan is automatically deselected.

=== Display training plan

I would like to see the training plan that is currently selected by me.

The plan view should present all trainings categorized into past, current and future trainings.
It should be possible to download a printable form of the plan (poster).

=== Display training

I would like to see the selected training.

The most important information regarding the training is its construction, i.e.:

* overall length,
* some additional characteristics such as intensity, difficulty, description,
* specification of all training compounds:
** intervals,
** RBIs,
** duration of each phase,
** additional requirements regarding each phase (such as expected power, HR, cadence, etc).

It should be possible to specify whether given training has been taken.
It should be also possible to upload training data (see <<Upload training data>> use case).
If the _evaluation_ of the taken training is available, it should be shown here as well.

=== Upload training data

I would like to upload training data gathered by my device so that it can be automatically matched with my training plan, analyzed and evaluated.

It should be possible to upload the files in following formats: `fit`, `tcx`, `gpx`.
Once uploaded, the file will be automatically processed.
The content of the file is analyzed and compared with training model.
The system then evaluates and assigns a score for the training.
The score is shown to the user in <<Display training>> use case.

=== Withdraw plan

I would like to stop execution of the plan, that has been previously selected.

A withdrawn plan can be resumed unless another training plan has been started.

=== Create training

I would like to create a training.

Once this use case is started, the Plan owner is taken to the training creator, where it is possible to specify all phases this training consists of.

=== Create training plan

I would like to create a new training plan.

Each plan can be either public (can be seen and taken by anyone) or private (only Plan owner can select it).

