= Requirements


== Actors

Cyclist:: A happy person that likes to sweat.
Plan Owner:: A person who creates training plans. Training plans can be created for private use or can be published for other cyclists' usage.


== User stories

[plantuml, actors, png]
....
skinparam handwritten true
left to right direction
:Cyclist:
:Plan Owner: as Trainer
(Training plan selection) as Select
(Display training plan) as DisplayPlan
(Upload training data) as Upload
(Display training) as DisplayTraining
(Withdraw plan) as Withdraw
(Evaluate training) as Evaluate
(Create indoor training) as CreateIndoorTraining
(Create training plan) as CreatePlan

:Cyclist: -up-> Select
:Cyclist: -up-> DisplayPlan
:Cyclist: -up-> Withdraw
:Cyclist: --> Upload
:Cyclist: --> DisplayTraining
:Cyclist: --> Evaluate
Trainer --> CreatePlan
Trainer --> CreateIndoorTraining
....


=== Training plan selection

I would like to select one of the available training plans.

The plan becomes immediately effective.
The plan stays selected until its last day, or until the cyclist selects <<Withdraw plan>> use case.
Once last day of the training plan passes, the plan is automatically deselected.


=== Display training plan

I would like to see the training plan that is currently selected by me.

The plan view should present all trainings categorized into past, current and future trainings.
It should be possible to download a printable form of the plan (poster).


=== Display training

I would like to see the selected training.

The most important information regarding the training is its construction, i.e.:

* overall length,
* some additional characteristics such as intensity, difficulty, description,
* specification of all training compounds:
** intervals,
** RBIs,
** duration of each phase,
** additional requirements regarding each phase (such as expected power, HR, cadence, etc).

It should be possible to specify whether given training has been taken.
It should be also possible to upload training data (see <<Upload training data>> use case).
If the _evaluation_ of the taken training is available, it should be shown here as well.


=== Upload training data

I would like to upload training data gathered by my device so that it can be automatically matched with my training plan, analyzed and evaluated.

It should be possible to upload the files in following formats: `fit`, `tcx`, `gpx`.
Once uploaded, the file will be automatically processed.
The content of the file is analyzed and compared with training model.
The system then evaluates and assigns a score for the training.
The score is shown to the user in <<Display training>> use case.


=== Withdraw plan

I would like to stop execution of the plan, that has been previously selected.

A withdrawn plan can be resumed unless another training plan has been started.


=== Create indoor training

I would like to create an indoor training.

Once this use case is started, the Plan owner is taken to the training creator, where it is possible to specify all phases this training consists of.

Usually the training consist of following phases:

. Warm up.
. Workout.
. Cool down.

We consider now only interval trainings, for such the _Workout_ is set of _intervals_, each, in the simplest case, consisting of _Work phase_ and _Rest phase_.

[#example-example-workout]
.Simple workout example
====
5x6 min MT, 3 min RBI
====

Let's take a look at <<example-example-workout>>: this is a very simple workout, and a very simple interval scheme.
Each piece of work is identical which says: use higher resistance on your home trainer and keep cadence low (let's say 75 -- 85 rpm).
For rest it will probably make sense just to reduce resistance.

[#example-complex-workout]
.Complex workout example
====
4x8 min OU, 4 min RBI:

* 3 min at Tempo HR & Power
* 1 min at Steady State HR & Power
* 3 min at Tempo HR & Power
* 1 min at Steady State HR & Power
====

At <<example-complex-workout>> we see a training with more complex layout.
The workout consists of 4 _intervals_ of 8 minutes, but each interval consists of two sub intervals: 3 minutes of higher intensity, 1 minute of slightly lower intensity. Then there are 4 minutes of rest.


=== Create training plan

I would like to create a new training plan.

Each plan can be either public (can be seen and taken by anyone) or private (only Plan owner can select it).
The training plan consists of stem:[n] weeks.
Each week consists of predefined amount of training days and rest days.
For each training day there is a training assigned.
